# Generated by Django 5.1.3 on 2024-11-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitAllBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bookID', models.IntegerField(default='-1')),
            ],
            options={
                'ordering': ('bookID',),
            },
        ),
        migrations.CreateModel(
            name='ProduitEnglishBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bookID', models.IntegerField(default='-1')),
            ],
            options={
                'ordering': ('bookID',),
            },
        ),
        migrations.CreateModel(
            name='ProduitFrenchBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bookID', models.IntegerField(default='-1')),
            ],
            options={
                'ordering': ('bookID',),
            },
        ),
    ]
