
dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/bmr?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Rongyaojiwuming0!


rules:
  - !SHARDING
    tables:
      t_user:

        actualDataNodes: ds_0.t_user_${0..15}

        tableStrategy:

          standard:

            shardingColumn: username

            shardingAlgorithmName: user_table_hash_mod
        keyGenerateStrategy:
          column: id
          keyGeneratorName: snowflake

      t_group:

        actualDataNodes: ds_0.t_group_${0..15}
        tableStrategy:
          standard:
            shardingColumn: username
            shardingAlgorithmName: user_group_hash_mod
        keyGenerateStrategy:
          column: id
          keyGeneratorName: snowflake



    shardingAlgorithms:

      user_table_hash_mod:
        type: HASH_MOD
        props:
          sharding-count: 16

      user_group_hash_mod:
        type: HASH_MOD
        props:
          sharding-count: 16

    keyGenerators:
      snowflake:
        type: SNOWFLAKE
        props:
          worker-id: 123

props:
  sql-show: true