# Generated by Django 3.1.4 on 2020-12-04 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytig', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tigredirect',
            new_name='ProduitEnPromotion',
        ),
    ]
